const quotesData = {
      arabic: [
        { quote: "اطلبوا العلم من المهد إلى اللحد.", author: "قول مأثور" },
{ quote: "العقل زينة.", author: "قول مأثور" },
{ quote: "الصبر مفتاح الفرج.", author: "مثل عربي" },
{ quote: "من جدّ وجد، ومن زرع حصد.", author: "مثل عربي" },
{ quote: "ليس الفخر أن لا تسقط، إنما الفخر أن تنهض كلما سقطت.", author: "علي بن أبي طالب" },
{ quote: "إذا أردت أن تطاع فأمر بما يستطاع.", author: "قول مأثور" },
{ quote: "كن جميلاً ترى الوجود جميلاً.", author: "إيليا أبو ماضي" },
{ quote: "اعمل لدنياك كأنك تعيش أبداً، واعمل لآخرتك كأنك تموت غداً.", author: "حديث نبوي" },
{ quote: "الرأي قبل شجاعة الشجعان.", author: "المتنبي" },
{ quote: "لا تؤجل عمل اليوم إلى الغد.", author: "مثل عربي" },
{ quote: "العلم نور والجهل ظلام.", author: "قول مأثور" },
{ quote: "الوقت كالسيف إن لم تقطعه قطعك.", author: "مثل عربي" },
{ quote: "النجاح لا يأتي بالحظ بل بالعمل والمثابرة.", author: "قول مأثور" },
{ quote: "من تواضع لله رفعه.", author: "حديث نبوي" },
{ quote: "رحم الله امرأً عرف قدر نفسه.", author: "علي بن أبي طالب" },
{ quote: "إذا لم تستحِ فاصنع ما شئت.", author: "حديث نبوي" },
{ quote: "ما نيل المطالب بالتمني، ولكن تؤخذ الدنيا غلابا.", author: "أحمد شوقي" },
{ quote: "الأمل يخلق من اليأس حياة.", author: "جبران خليل جبران" },
{ quote: "إذا الشعب يوماً أراد الحياة فلا بد أن يستجيب القدر.", author: "أبو القاسم الشابي" },
{ quote: "الكلمة الطيبة صدقة.", author: "حديث نبوي" },
{ quote: "لا خاب من استشار.", author: "مثل عربي" },
{ quote: "العقل السليم في الجسم السليم.", author: "قول مأثور" },
{ quote: "من سار على الدرب وصل.", author: "مثل عربي" },
{ quote: "ابتسم فإن الابتسامة في وجه أخيك صدقة.", author: "حديث نبوي" },
{ quote: "التواضع من شيم الكبار.", author: "قول مأثور" },
{ quote: "من لم يشكر الناس لا يشكر الله.", author: "حديث نبوي" },
{ quote: "الصدق منجاة.", author: "حديث نبوي" },
{ quote: "خير الأمور أوسطها.", author: "حديث نبوي" },
{ quote: "الحرية شمس يجب أن تشرق في كل نفس.", author: "مصطفى لطفي المنفلوطي" },
{ quote: "العبرة بالخواتيم.", author: "قول مأثور" },
{ quote: "السكوت علامة الرضا.", author: "مثل عربي" },
{ quote: "الصديق وقت الضيق.", author: "مثل عربي" },
{ quote: "إذا أردت أن تُحَب، فكن صادقاً.", author: "قول مأثور" },
{ quote: "من راقب الناس مات همًا.", author: "قول مأثور" },
{ quote: "العين لا تعلو على الحاجب.", author: "مثل عربي" },
{ quote: "العز في الطاعة، والذل في المعصية.", author: "قول مأثور" },
{ quote: "النجاح رحلة وليس هدفاً.", author: "قول مأثور" },
{ quote: "العقل يفكر، والقلب يقرر.", author: "قول مأثور" },
{ quote: "العمل عبادة.", author: "حديث نبوي" },
{ quote: "التجربة خير برهان.", author: "مثل عربي" },
{ quote: "الحق يعلو ولا يُعلى عليه.", author: "قول مأثور" },
{ quote: "العزيمة تصنع المستحيل.", author: "قول مأثور" },
{ quote: "الطيبة لا تعني الغباء.", author: "قول مأثور" },
{ quote: "لا تنهَ عن خلق وتأتي مثله.", author: "قول مأثور" },
{ quote: "كل مر سيمر.", author: "قول مأثور" },
{ quote: "الناس نيام، فإذا ماتوا انتبهوا.", author: "الإمام علي بن أبي طالب" },
{ quote: "الحكمة ضالة المؤمن.", author: "حديث نبوي" },
{ quote: "من أحب الله رأى كل شيء جميلاً.", author: "قول مأثور" },
{ quote: "الإرادة تصنع الطريق.", author: "قول مأثور" },
{ quote: "حياتك من صنع أفكارك.", author: "قول مأثور" },
{ quote: "لا يُدرَك النجاح إلا بالصبر والعمل.", author: "قول مأثور" },
{ quote: "إذا كان الكلام من فضة، فالسكوت من ذهب.", author: "مثل عربي" },
{ quote: "من علمني حرفاً كنت له عبداً.", author: "قول مأثور" },
{ quote: "العبرة ليست في البدايات، إنما في النهايات.", author: "قول مأثور" },
{ quote: "الدنيا ساعة فاجعلها طاعة.", author: "قول مأثور" },
{ quote: "كل شيء إذا كثر رخص إلا الأدب، فإنه إذا كثر غلا.", author: "قول مأثور" },
{ quote: "من لم يذق مر التعلم ساعة، تجرع ذل الجهل طول حياته.", author: "قول مأثور" },
{ quote: "اعرف نفسك تعرف ربك.", author: "قول مأثور" },
{ quote: "أعظم النصر هو الانتصار على النفس.", author: "قول مأثور" },
{ quote: "ما خرج من القلب يصل إلى القلب.", author: "قول مأثور" },
{ quote: "الحياء لا يأتي إلا بخير.", author: "حديث نبوي" },
{ quote: "لا تحقرن من المعروف شيئًا.", author: "حديث نبوي" },
{ quote: "عامل الناس كما تحب أن يعاملوك.", author: "قول مأثور" },
{ quote: "القناعة كنز لا يفنى.", author: "مثل عربي" },
{ quote: "القلوب الطيبة لا تنسى الخير أبداً.", author: "قول مأثور" },
{ quote: "الأمانة أساس النجاح.", author: "قول مأثور" },
{ quote: "من طلب العلا سهر الليالي.", author: "مثل عربي" },
{ quote: "ليس كل ما يُعرف يُقال.", author: "قول مأثور" },
{ quote: "من سار على هدى ربه فلن يضل.", author: "قول مأثور" },
{ quote: "لا يوجد مستحيل مع الإصرار.", author: "قول مأثور" },
{ quote: "اجعل بينك وبين الناس شعرة، فإذا شدوها أرخيتها.", author: "معاوية بن أبي سفيان" },
{ quote: "الجاهل عدو نفسه.", author: "قول مأثور" },
{ quote: "لا تنظر إلى من قال، بل انظر إلى ما قال.", author: "قول مأثور" },
{ quote: "العقل الراجح يعرف متى يتكلم ومتى يصمت.", author: "قول مأثور" },
{ quote: "القوة الحقيقية هي ضبط النفس عند الغضب.", author: "حديث نبوي" },
{ quote: "اجعل لك هدفاً في الحياة واسعَ لتحقيقه.", author: "قول مأثور" },
{ quote: "الأمل هو النافذة التي تفتح الحياة.", author: "قول مأثور" },
{ quote: "أفضل الجهاد كلمة حق عند سلطان جائر.", author: "حديث نبوي" },
{ quote: "في كل محنة منحة.", author: "قول مأثور" },
{ quote: "السعادة قرار، لا تنتظرها من أحد.", author: "قول مأثور" },
{ quote: "افعل الخير ولو في غير أهله.", author: "قول مأثور" },
{ quote: "من لا يشكر الناس، لا يشكر الله.", author: "حديث نبوي" },
{ quote: "الحياة قصيرة فلا تضيعها في الحقد.", author: "قول مأثور" },
{ quote: "أجمل النفوس هي التي لا تنسى المعروف.", author: "قول مأثور" },
{ quote: "من ترك شيئًا لله عوضه الله خيرًا منه.", author: "قول مأثور" },
{ quote: "النجاح لا يُقاس بالمكان الذي وصلت إليه، بل بالعقبات التي تغلبت عليها.", author: "قول مأثور" },
{ quote: "تعلم متى ترحل بصمت دون أن تجرح أحداً.", author: "قول مأثور" },
{ quote: "المؤمن القوي خير وأحب إلى الله من المؤمن الضعيف.", author: "حديث نبوي" },
{ quote: "الكلمة الطيبة جواز مرور إلى قلوب الآخرين.", author: "قول مأثور" },
{ quote: "اجعل لكل يوم هدفًا وإنجازًا.", author: "قول مأثور" },
{ quote: "العلاقات تبنى على الاحترام لا على الإجبار.", author: "قول مأثور" },
{ quote: "الندم لا يعيد شيئًا، لكنه يعلم كثيرًا.", author: "قول مأثور" },
{ quote: "لا تتكلم إذا لم يكن لك شيء أفضل من الصمت.", author: "قول مأثور" },
{ quote: "عش بسيطًا تحيا سعيدًا.", author: "قول مأثور" },
{ quote: "من يحبك لا يؤذيك.", author: "قول مأثور" },
{ quote: "احترامك للناس لا يعني ضعفك.", author: "قول مأثور" },
{ quote: "لا تفقد الأمل، فالمعجزات تولد من رحم اليأس.", author: "قول مأثور" },
{ quote: "القلوب الطيبة لا تتغير مهما جرحها الزمن.", author: "قول مأثور" },
{ quote: "سقوط الإنسان ليس فشلًا، الفشل أن يبقى حيث سقط.", author: "قول مأثور" },
{ quote: "العبرة ليست بمن سبق، بل بمن ثبت.", author: "قول مأثور" },
{ quote: "لا تحزن إذا خسرت شيئًا عزيزًا، فقد تكسب أشياء أعظم.", author: "قول مأثور" },
{ quote: "الصبر مفتاح الفرج.", author: "مثل عربي" },
{ quote: "النجاح رحلة، وليس نقطة وصول.", author: "قول مأثور" },
{ quote: "من جد وجد، ومن زرع حصد.", author: "مثل عربي" },
{ quote: "ليس العار أن تسقط، بل العار أن تبقى حيث سقطت.", author: "قول مأثور" },
{ quote: "الإرادة تصنع المعجزات.", author: "قول مأثور" },
{ quote: "أعظم الحكمة أن تعرف متى تتكلم ومتى تصمت.", author: "قول مأثور" },
{ quote: "الوقت كالسيف إن لم تقطعه قطعك.", author: "مثل عربي" },
{ quote: "الأمل هو الطاقة التي تدفع الإنسان نحو الأفضل.", author: "قول مأثور" },
{ quote: "لا شيء يستحق أن تفقد نفسك من أجله.", author: "قول مأثور" },
{ quote: "العقل زينة، فلا تهدره في القلق.", author: "قول مأثور" },
{ quote: "التغيير يبدأ من الداخل.", author: "قول مأثور" },
{ quote: "كن أنت التغيير الذي تريد أن تراه في العالم.", author: "جمال الدين الأفغاني" },
{ quote: "العطاء هو أثمن عمل إنساني.", author: "قول مأثور" },
{ quote: "ليس الجمال بأثواب تزيننا، إن الجمال جمال العلم والأدب.", author: "قول مأثور" },
{ quote: "النجاح لا يأتي بالصدفة، بل بالمثابرة.", author: "قول مأثور" },
{ quote: "إياك أن تستسلم مهما كانت الظروف.", author: "قول مأثور" },
{ quote: "الصداقة الحقيقية هي أن تظل بجانب صديقك في أوقات الشدة.", author: "قول مأثور" },
{ quote: "العمل عبادة، فلا تهدر وقتك.", author: "قول مأثور" },
{ quote: "العقل لا يقبل الهزيمة إذا أراد الانتصار.", author: "قول مأثور" },
{ quote: "تعلم من أخطائك، فهي أصدق معلم.", author: "قول مأثور" },
{ quote: "الحياة اختبار مستمر، فكن مستعدًا دائمًا.", author: "قول مأثور" },
{ quote: "الحرية لا تعني الفوضى، بل المسؤولية.", author: "قول مأثور" },
{ quote: "من يزرع حبًا يحصد احترامًا.", author: "قول مأثور" },
{ quote: "كل يوم فرصة جديدة لتصحيح المسار.", author: "قول مأثور" },
{ quote: "لا تخف من الفشل، فهو خطوة نحو النجاح.", author: "قول مأثور" },
{ quote: "الصدق منجاة.", author: "مثل عربي" },
{ quote: "العلم نور والجهل ظلام.", author: "قول مأثور" },
{ quote: "لا تترك حلمك يموت في أعماقك.", author: "قول مأثور" },
{ quote: "القلب الصادق لا يعرف الكذب.", author: "قول مأثور" },
{ quote: "كل بداية صعبة، لكن الإصرار يصنع الفرق.", author: "قول مأثور" },
{ quote: "الكرم عنوان الكبار.", author: "قول مأثور" },
{ quote: "تعلم أن تقول لا، لتحمي نفسك.", author: "قول مأثور" },
{ quote: "الحكمة ضالة المؤمن.", author: "حديث نبوي" },
{ quote: "لا تنتظر الفرصة، بل اصنعها.", author: "قول مأثور" },
{ quote: "الأفعال أبلغ من الأقوال.", author: "قول مأثور" },
{ quote: "إذا أردت أن تضيء شمعة، فلا تلعن الظلام.", author: "قول مأثور" },
{ quote: "الكرامة أغلى من المال.", author: "قول مأثور" },
{ quote: "الصمت حكمة في كثير من الأحيان.", author: "قول مأثور" },
{ quote: "النجاح يبدأ بخطوة.", author: "قول مأثور" },
{ quote: "الصدق رأس المال في العلاقات.", author: "قول مأثور" },
{ quote: "تعلم من الماضي، عش الحاضر، وأمل المستقبل.", author: "قول مأثور" },
{ quote: "السعادة قرار، فاخترها.", author: "قول مأثور" },
{ quote: "العطاء من دون انتظار مقابل، هو أجمل أنواع السعادة.", author: "قول مأثور" },
{ quote: "لا تقلق، فبعد العسر يأتي اليسر.", author: "قول مأثور" },
{ quote: "العقل السليم في الجسم السليم.", author: "مثل عربي" },
{ quote: "النجاح يتطلب الصبر والمثابرة.", author: "قول مأثور" },
{ quote: "لا تيأس، فكل شيء سيصبح أفضل.", author: "قول مأثور" },
{ quote: "المحبة أساس الحياة.", author: "قول مأثور" },
{ quote: "لا تجعل الأمس يسرق منك اليوم.", author: "قول مأثور" },
{ quote: "الحياة ليست انتظار العاصفة، بل تعلم كيف ترقص تحت المطر.", author: "قول مأثور" },
{ quote: "العزيمة تقهر المستحيل.", author: "قول مأثور" },
{ quote: "ليس المهم أن تكون الأفضل، بل أن تكون أنت أفضل نسخة من نفسك.", author: "قول مأثور" },
{ quote: "السعادة تكمن في القناعة.", author: "قول مأثور" },
{ quote: "القوة الحقيقية هي السيطرة على النفس.", author: "قول مأثور" },
{ quote: "لا تؤجل عمل اليوم إلى الغد.", author: "مثل عربي" },
{ quote: "النجاح يبدأ بالإيمان.", author: "قول مأثور" },
{ quote: "لا شيء يستحق أن تخاف منه.", author: "قول مأثور" },
{ quote: "الابتسامة طريق إلى قلوب الناس.", author: "قول مأثور" },
{ quote: "كل حلم يبدأ بخطوة.", author: "قول مأثور" },
{ quote: "العقل هو أفضل سلاح تملكه.", author: "قول مأثور" },
{ quote: "المعرفة هي قوة.", author: "فرانسيس بيكون" },
{ quote: "لا تخف من التغيير، فهو مفتاح التقدم.", author: "قول مأثور" },
{ quote: "أجمل الأشياء لا تُشترى بالمال.", author: "قول مأثور" },
{ quote: "كن كما أنت ولا تحاول أن تكون شخصًا آخر.", author: "قول مأثور" },
{ quote: "الأمل هو سر الحياة.", author: "قول مأثور" },
{ quote: "لا تدع اليأس يسرق منك أحلامك.", author: "قول مأثور" },
{ quote: "القناعة كنز لا يفنى.", author: "مثل عربي" },
{ quote: "العطاء يعيد للحياة جمالها.", author: "قول مأثور" },
{ quote: "كن قويًا في وجه العواصف.", author: "قول مأثور" },
{ quote: "النجاح يحتاج إلى جهد مستمر.", author: "قول مأثور" },
{ quote: "الحكمة تأتي من التجربة.", author: "قول مأثور" },
{ quote: "لا تقف عند الفشل، بل انهض بسرعة.", author: "قول مأثور" },
{ quote: "الوقت هو أثمن ما نملك.", author: "قول مأثور" },
{ quote: "لا يوجد شيء مستحيل لمن يؤمن بنفسه.", author: "قول مأثور" },
{ quote: "العقل زينة والخلق حسنة.", author: "قول مأثور" },
{ quote: "تعلّم كيف تحب نفسك أولًا.", author: "قول مأثور" },
{ quote: "النجاح يبدأ بخطة واضحة.", author: "قول مأثور" },
{ quote: "الابتسامة لا تكلف شيئًا لكنها تعني الكثير.", author: "قول مأثور" },
{ quote: "احرص على قول الحق، حتى وإن كان صعبًا.", author: "قول مأثور" },
{ quote: "ليس الفشل أن تقع، بل أن تبقى حيث وقعت.", author: "قول مأثور" },
{ quote: "كل تحدي هو فرصة للنمو.", author: "قول مأثور" },
{ quote: "لا تتوقف عن التعلم أبدًا.", author: "قول مأثور" },
{ quote: "قوة الإنسان في ثقته بنفسه.", author: "قول مأثور" },
{ quote: "الحب هو أجمل شعور في الحياة.", author: "قول مأثور" },
{ quote: "إياك واليأس، فبعد الليل يأتي الصباح.", author: "قول مأثور" },
{ quote: "لا تخف أن تكون مختلفًا.", author: "قول مأثور" },
{ quote: "احترام الآخرين هو مفتاح الاحترام.", author: "قول مأثور" },
{ quote: "القوة لا تعني السيطرة، بل التسامح.", author: "قول مأثور" },
{ quote: "الأمل هو بداية كل نجاح.", author: "قول مأثور" },
{ quote: "النجاح الحقيقي هو أن تحقق ذاتك.", author: "قول مأثور" },
{ quote: "العزيمة تصنع المعجزات.", author: "قول مأثور" },
{ quote: "لا تكن عبداً للماضي، بل صاحب مستقبل.", author: "قول مأثور" },
{ quote: "كن صادقًا مع نفسك، وستكون صادقًا مع الآخرين.", author: "قول مأثور" },
{ quote: "العيش في اللحظة هو سر السعادة.", author: "قول مأثور" },
{ quote: "الإيمان هو مفتاح كل خير.", author: "قول مأثور" },
{ quote: "العقل زينة الإنسان.", author: "قول مأثور" },
{ quote: "الأمل هو الحياة الثانية للإنسان.", author: "قول مأثور" },
{ quote: "لا شيء يدوم إلا التغيير.", author: "قول مأثور" },
{ quote: "اصنع لنفسك تاريخاً تُروى به قصص النجاح.", author: "قول مأثور" },
{ quote: "كل بداية صعبة، لكن المثابرة تصنع الفرق.", author: "قول مأثور" },
{ quote: "العلم نور والجهل ظلام.", author: "قول مأثور" },
{ quote: "ثق بنفسك، فالثقة نصف النجاح.", author: "قول مأثور" },
{ quote: "الصبر مفتاح الفرج.", author: "مثل عربي" },
{ quote: "النجاح رحلة، لا محطة.", author: "قول مأثور" },
{ quote: "العمل بجد يفوق المواهب.", author: "قول مأثور" },
{ quote: "الابتسامة سرٌ لجذب القلوب.", author: "قول مأثور" },
{ quote: "عش حياتك كما تريد أن يتذكرك الناس.", author: "قول مأثور" },
{ quote: "النجاح يحتاج إلى شجاعة.", author: "قول مأثور" },
{ quote: "كن السبب في سعادة أحدهم اليوم.", author: "قول مأثور" },
{ quote: "الوقت لا يعود، فاستغله جيداً.", author: "قول مأثور" },
{ quote: "حلمك لا يستحق التوقف عنه.", author: "قول مأثور" },
{ quote: "الصداقة كنز لا يفنى.", author: "قول مأثور" },
{ quote: "أنت من تصنع الفرق في حياتك.", author: "قول مأثور" },
{ quote: "لا تقل مستحيل، فالكلمة تحكم عقلك.", author: "قول مأثور" },
{ quote: "الإنسان لا يُقاس بما يملك، بل بما يعطي.", author: "قول مأثور" },
{ quote: "الجمال الحقيقي ينبع من الداخل.", author: "قول مأثور" },
{ quote: "التواضع زينة العقلاء.", author: "قول مأثور" },
{ quote: "القراءة هي نافذة العقل.", author: "قول مأثور" },
{ quote: "لا تدع الخوف يمنعك من المحاولة.", author: "قول مأثور" },
{ quote: "حاول، تفشل، تعلم، وكرر.", author: "قول مأثور" },
{ quote: "السعادة اختيار، فاخترها كل يوم.", author: "قول مأثور" },
{ quote: "النجاح يبدأ بخطوة.", author: "قول مأثور" },
{ quote: "لا تستسلم مهما كانت الظروف.", author: "قول مأثور" },
{ quote: "الحكمة في الصمت أحياناً.", author: "قول مأثور" },
{ quote: "كل شيء جميل يحتاج إلى وقت.", author: "قول مأثور" },
{ quote: "ابتسم للحياة، فهي تبتسم لك.", author: "قول مأثور" },
{ quote: "الثقة بالله مفتاح الفرج.", author: "قول مأثور" },
{ quote: "لا تكن عبداً للماضي، بل صاحب مستقبل.", author: "قول مأثور" },
{ quote: "الإرادة تصنع المعجزات.", author: "قول مأثور" },
{ quote: "كن أنت التغيير الذي تريد رؤيته.", author: "قول مأثور" },
{ quote: "لا تنتظر الفرصة، اصنعها.", author: "قول مأثور" },
{ quote: "النجاح لا يأتي صدفة.", author: "قول مأثور" },
{ quote: "القوة في العزيمة والإصرار.", author: "قول مأثور" },
{ quote: "كن لطيفاً مع من حولك.", author: "قول مأثور" },
{ quote: "العطاء يضاعف السعادة.", author: "قول مأثور" },
{ quote: "العقل الواعي هو السبيل للنجاح.", author: "قول مأثور" },
{ quote: "العمل هو طريق المجد.", author: "قول مأثور" },
{ quote: "الإيجابية تجذب الإيجابية.", author: "قول مأثور" },
{ quote: "التفاؤل هو سر النجاح.", author: "قول مأثور" },
{ quote: "الحياة مغامرة جريئة أو لا شيء.", author: "هيلين كيلر" },
{ quote: "الكرم يفتح أبواب الخير.", author: "قول مأثور" },
{ quote: "لا تجعل الفشل نهاية القصة.", author: "قول مأثور" },
{ quote: "ثق بنفسك، فأنت قادر على كل شيء.", author: "قول مأثور" },
{ quote: "الحب هو لغة القلوب.", author: "قول مأثور" },
{ quote: "ابدأ الآن، لا تنتظر الغد.", author: "قول مأثور" },
{ quote: "كن سبباً في تغيير حياة شخص.", author: "قول مأثور" },

      ],
      english: [
        { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
  { quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
  { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { quote: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
  { quote: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { quote: "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
  { quote: "Limit your 'always' and your 'nevers'.", author: "Amy Poehler" },
  { quote: "Try to be a rainbow in someone's cloud.", author: "Maya Angelou" },
  { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { quote: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
  { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { quote: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { quote: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen R. Covey" },
  { quote: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
  { quote: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { quote: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { quote: "To be the best, you must be able to handle the worst.", author: "Wilson Kanadi" },
  { quote: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { quote: "Whether you think you can or you think you can’t, you’re right.", author: "Henry Ford" },
  { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
  { quote: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
  { quote: "Do not wait for the perfect moment. Take the moment and make it perfect.", author: "Zoey Sayward" },
  { quote: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { quote: "Perseverance is not a long race; it's many short races one after the other.", author: "Walter Elliot" },
  { quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { quote: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
  { quote: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
  { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { quote: "You can’t use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
  { quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { quote: "Small deeds done are better than great deeds planned.", author: "Peter Marshall" },
  { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
{ quote: "The best way to predict the future is to create it.", author: "Peter Drucker" },
{ quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
{ quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
{ quote: "Act as if what you do makes a difference. It does.", author: "William James" },
{ quote: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
{ quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
{ quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
{ quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
{ quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
{ quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
{ quote: "The harder the conflict, the more glorious the triumph.", author: "Thomas Paine" },
{ quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
{ quote: "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.", author: "Jimmy Dean" },
{ quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
{ quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
{ quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
{ quote: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
{ quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
{ quote: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
{ quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
{ quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
{ quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
{ quote: "Don't limit your challenges. Challenge your limits.", author: "Jerry Dunn" },
{ quote: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
{ quote: "Only those who dare to fail greatly can ever achieve greatly.", author: "Robert F. Kennedy" },
{ quote: "If you're going through hell, keep going.", author: "Winston Churchill" },
{ quote: "There is nothing impossible to they who will try.", author: "Alexander the Great" },
{ quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
{ quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
{ quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
{ quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
{ quote: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein" },
{ quote: "Don't wait. The time will never be just right.", author: "Napoleon Hill" },
{ quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
{ quote: "Success is stumbling from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
{ quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
{ quote: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
{ quote: "Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do.", author: "Unknown" },
{ quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
{ quote: "Don't quit. Suffer now and live the rest of your life as a champion.", author: "Muhammad Ali" },
{ quote: "One person can make a difference, and everyone should try.", author: "John F. Kennedy" },
{ quote: "Work hard in silence, let success make the noise.", author: "Frank Ocean" },
{ quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
{ quote: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
{ quote: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
{ quote: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
{ quote: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
{ quote: "Small deeds done are better than great deeds planned.", author: "Peter Marshall" },
{ quote: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
{ quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
{ quote: "The best way out is always through.", author: "Robert Frost" },
{ quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
{ quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
{ quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
{ quote: "Dream it. Wish it. Do it.", author: "Unknown" },
{ quote: "Little by little, a little becomes a lot.", author: "Tanzanian Proverb" },
{ quote: "Don’t stop when you’re tired. Stop when you’re done.", author: "Marilyn Monroe" },
{ quote: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown" },
{ quote: "Great things never come from comfort zones.", author: "Unknown" },
{ quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
{ quote: "Sometimes later becomes never. Do it now.", author: "Unknown" },
{ quote: "Don’t wait for opportunity. Create it.", author: "Unknown" },
{ quote: "It’s going to be hard, but hard does not mean impossible.", author: "Unknown" },
{ quote: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
{ quote: "Success is what comes after you stop making excuses.", author: "Unknown" },
{ quote: "Your limitation—it’s only your imagination.", author: "Unknown" },
{ quote: "Great things take time. Be patient.", author: "Unknown" },
{ quote: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier" },
{ quote: "Don’t wish it were easier. Wish you were better.", author: "Jim Rohn" },
{ quote: "You are capable of amazing things.", author: "Unknown" },
{ quote: "Make each day your masterpiece.", author: "John Wooden" },
{ quote: "Failure is the condiment that gives success its flavor.", author: "Truman Capote" },
{ quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
{ quote: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
{ quote: "If you want to fly, give up everything that weighs you down.", author: "Buddha" },
{ quote: "Success is not for the lazy.", author: "Unknown" },
{ quote: "Dream big, work hard, stay focused.", author: "Unknown" },
{ quote: "The secret of success is constancy of purpose.", author: "Benjamin Disraeli" },
{ quote: "Don’t limit your challenges. Challenge your limits.", author: "Unknown" },
{ quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
{ quote: "The expert in anything was once a beginner.", author: "Helen Hayes" },
{ quote: "If it doesn’t challenge you, it won’t change you.", author: "Fred DeVito" },
{ quote: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
{ quote: "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", author: "Unknown" },
{ quote: "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
{ quote: "When you feel like quitting, think about why you started.", author: "Unknown" },
{ quote: "Don’t stop until you’re proud.", author: "Unknown" },
{ quote: "You don’t always get what you wish for; you get what you work for.", author: "Unknown" },
{ quote: "A little progress each day adds up to big results.", author: "Satya Nani" },
{ quote: "The only limits that exist are the ones in your own mind.", author: "Unknown" },
{ quote: "Sometimes the smallest step in the right direction ends up being the biggest step of your life.", author: "Naeem Callaway" },
{ quote: "Don’t quit. Suffer now and live the rest of your life as a champion.", author: "Muhammad Ali" },
{ quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
{ quote: "Don’t be afraid to fail. Be afraid not to try.", author: "Michael Jordan" },
{ quote: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
{ quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
{ quote: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
{ quote: "Act as if what you do makes a difference. It does.", author: "William James" },
{ quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
{ quote: "Don’t be distracted by criticism. Remember—the only taste of success some people get is to take a bite out of you.", author: "Zig Ziglar" },
{ quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
{ quote: "If you want something you’ve never had, you must be willing to do something you’ve never done.", author: "Thomas Jefferson" },
{ quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
{ quote: "Be miserable. Or motivate yourself. Whatever has to be done, it’s always your choice.", author: "Wayne Dyer" },
{ quote: "The future depends on what you do today.", author: "Mahatma Gandhi" },
{ quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
{ quote: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
{ quote: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein" },
{ quote: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
{ quote: "Your passion is waiting for your courage to catch up.", author: "Isabelle Lafleche" },
{ quote: "Magic is believing in yourself, if you can do that, you can make anything happen.", author: "Johann Wolfgang von Goethe" },
{ quote: "Don’t let what you cannot do interfere with what you can do.", author: "John Wooden" },
{ quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
{ quote: "Hustle in silence and let your success make the noise.", author: "Unknown" },
{ quote: "When you arise in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius" },
{ quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
{ quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
{ quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
{ quote: "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.", author: "Jimmy Dean" },
{ quote: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Rohn" },
{ quote: "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.", author: "Earl Nightingale" },
{ quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
{ quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
{ quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
{ quote: "Don’t wait for opportunity. Create it.", author: "George Bernard Shaw" },
{ quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
{ quote: "The harder the conflict, the greater the triumph.", author: "George Washington" },
{ quote: "Only those who dare to fail greatly can ever achieve greatly.", author: "Robert F. Kennedy" },
{ quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
{ quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
{ quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
{ quote: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
{ quote: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein" },
{ quote: "Your time is limited, don’t waste it living someone else’s life.", author: "Steve Jobs" },
{ quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
{ quote: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
{ quote: "Believe in yourself and all that you are.", author: "Christian D. Larson" },
{ quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
{ quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
{ quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
{ quote: "I never dreamed about success. I worked for it.", author: "Estée Lauder" },
{ quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
{ quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
{ quote: "Be not afraid of going slowly, be afraid only of standing still.", author: "Chinese Proverb" },
      ],

       movie: [
  { quote: "May the Force be with you.", author: "Star Wars" },
  { quote: "I'm gonna make him an offer he can't refuse.", author: "The Godfather" },
  { quote: "Here's looking at you, kid.", author: "Casablanca" },
  { quote: "Why so serious?", author: "The Dark Knight" },
  { quote: "To infinity and beyond!", author: "Toy Story" },
  { quote: "I see dead people.", author: "The Sixth Sense" },
  { quote: "I'll be back.", author: "The Terminator" },
  { quote: "You can't handle the truth!", author: "A Few Good Men" },
  { quote: "Keep your friends close, but your enemies closer.", author: "The Godfather Part II" },
  { quote: "Just keep swimming.", author: "Finding Nemo" },
  { quote: "Houston, we have a problem.", author: "Apollo 13" },
  { quote: "I feel the need—the need for speed!", author: "Top Gun" },
  { quote: "There's no place like home.", author: "The Wizard of Oz" },
  { quote: "You're gonna need a bigger boat.", author: "Jaws" },
  { quote: "I'll have what she's having.", author: "When Harry Met Sally" },
  { quote: "Say hello to my little friend!", author: "Scarface" },
  { quote: "Here's Johnny!", author: "The Shining" },
  { quote: "Life is like a box of chocolates.", author: "Forrest Gump" },
  { quote: "To me, you are perfect.", author: "Love Actually" },
  { quote: "I see you.", author: "Avatar" },
  { quote: "You talkin' to me?", author: "Taxi Driver" },
  { quote: "I am your father.", author: "Star Wars: The Empire Strikes Back" },
  { quote: "Why did it have to be snakes?", author: "Raiders of the Lost Ark" },
  { quote: "They may take our lives, but they'll never take our freedom!", author: "Braveheart" },
  { quote: "I'm the king of the world!", author: "Titanic" },
  { quote: "It’s alive! It’s alive!", author: "Frankenstein" },
  { quote: "You're killin' me, Smalls!", author: "The Sandlot" },
  { quote: "This is Sparta!", author: "300" },
  { quote: "Keep the change, ya filthy animal!", author: "Home Alone" },
  { quote: "You can't sit with us!", author: "Mean Girls" },
  { quote: "I drink your milkshake!", author: "There Will Be Blood" },
  { quote: "You is kind. You is smart. You is important.", author: "The Help" },
  { quote: "With great power comes great responsibility.", author: "Spider-Man" },
  { quote: "You complete me.", author: "Jerry Maguire" },
  { quote: "I'm flying!", author: "Titanic" },
  { quote: "You make me want to be a better man.", author: "As Good as It Gets" },
  { quote: "Nobody puts Baby in a corner.", author: "Dirty Dancing" },
  { quote: "It’s not who I am underneath, but what I do that defines me.", author: "Batman Begins" },
  { quote: "I wish I knew how to quit you.", author: "Brokeback Mountain" },
  { quote: "I'm not a smart man, but I know what love is.", author: "Forrest Gump" },
  { quote: "You had me at hello.", author: "Jerry Maguire" },
  { quote: "Roads? Where we're going, we don't need roads.", author: "Back to the Future" },
  { quote: "I volunteer as tribute!", author: "The Hunger Games" },
  { quote: "I'm just a girl, standing in front of a boy, asking him to love her.", author: "Notting Hill" },
  { quote: "That'll do, pig. That'll do.", author: "Babe" },
  { quote: "Carpe diem. Seize the day, boys.", author: "Dead Poets Society" },
  { quote: "I'm walking here! I'm walking here!", author: "Midnight Cowboy" },
  { quote: "Elementary, my dear Watson.", author: "The Adventures of Sherlock Holmes" },
  { quote: "I am Iron Man.", author: "Iron Man" },
  { quote: "Just when I thought I was out, they pull me back in.", author: "The Godfather Part III" },
  { quote: "You're tearing me apart, Lisa!", author: "The Room" },
  { quote: "I'm having an old friend for dinner.", author: "The Silence of the Lambs" },
  { quote: "We’re not in Kansas anymore.", author: "The Wizard of Oz" },
  { quote: "They call it a Royale with cheese.", author: "Pulp Fiction" },
  { quote: "We all go a little mad sometimes.", author: "Psycho" },
  { quote: "Hakuna Matata!", author: "The Lion King" },
  { quote: "I'm gonna steal the Declaration of Independence.", author: "National Treasure" },
  { quote: "I'm not bad. I'm just drawn that way.", author: "Who Framed Roger Rabbit" },
  { quote: "I'm the Dude, so that's what you call me.", author: "The Big Lebowski" },
  { quote: "You either die a hero, or you live long enough to see yourself become the villain.", author: "The Dark Knight" },
  { quote: "I solemnly swear that I am up to no good.", author: "Harry Potter and the Prisoner of Azkaban" },
  { quote: "After all, tomorrow is another day!", author: "Gone with the Wind" },
  { quote: "We rob banks.", author: "Bonnie and Clyde" },
  { quote: "That rug really tied the room together.", author: "The Big Lebowski" },
  { quote: "Get busy living, or get busy dying.", author: "The Shawshank Redemption" },
  { quote: "I coulda been a contender.", author: "On the Waterfront" },
  { quote: "Greed, for lack of a better word, is good.", author: "Wall Street" },
  { quote: "I'm just one stomach flu away from my goal weight.", author: "The Devil Wears Prada" },
  { quote: "Wakanda forever!", author: "Black Panther" },
  { quote: "I've always depended on the kindness of strangers.", author: "A Streetcar Named Desire" },
  { quote: "As God is my witness, I'll never be hungry again.", author: "Gone with the Wind" },
  { quote: "Toto, I've a feeling we're not in Kansas anymore.", author: "The Wizard of Oz" },
  { quote: "Love means never having to say you're sorry.", author: "Love Story" },
  { quote: "Freedom!", author: "Braveheart" },
  { quote: "Hasta la vista, baby.", author: "Terminator 2: Judgment Day" },
  { quote: "Oh yes, the past can hurt. But you can either run from it, or learn from it.", author: "The Lion King" },
  { quote: "Sometimes it is the people who no one imagines anything of who do the things that no one can imagine.", author: "The Imitation Game" },
  { quote: "My precious.", author: "The Lord of the Rings: The Two Towers" },
  { quote: "The first rule of Fight Club is: You do not talk about Fight Club.", author: "Fight Club" },
  { quote: "You're a wizard, Harry.", author: "Harry Potter and the Sorcerer's Stone" },
  { quote: "I am Groot.", author: "Guardians of the Galaxy" },
  { quote: "Welcome to Jurassic Park.", author: "Jurassic Park" },
  { quote: "It’s so fluffy I’m gonna die!", author: "Despicable Me" },
  { quote: "There's a snake in my boot!", author: "Toy Story" },
  { quote: "You're a mean one, Mr. Grinch.", author: "How the Grinch Stole Christmas" },
  { quote: "I don't want to survive. I want to live.", author: "12 Years a Slave" },
  { quote: "You shall not pass!", author: "The Lord of the Rings: The Fellowship of the Ring" },
  { quote: "It’s called a hustle, sweetheart.", author: "Zootopia" },
  { quote: "It’s not personal, Sonny. It’s strictly business.", author: "The Godfather" },
  { quote: "I just wanted to take another look at you.", author: "A Star Is Born" },
  { quote: "If you build it, he will come.", author: "Field of Dreams" },
  { quote: "I'm the best there is at what I do.", author: "X-Men Origins: Wolverine" },

      ]
    };
    window.quotesData = quotesData;
